# Generated by Django 3.1 on 2020-10-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('1', '正在进行'), ('2', '已关闭')], default='1', max_length=16, verbose_name='状态'),
        ),
    ]
