# Generated by Django 3.1 on 2020-10-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_paper_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSubjective',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20, verbose_name='科目')),
                ('title', models.TextField(verbose_name='题目')),
                ('answer', models.TextField(null=True, verbose_name='参考答案')),
                ('score', models.IntegerField(verbose_name='分数')),
            ],
            options={
                'verbose_name': '主观题',
                'verbose_name_plural': '主观题',
                'db_table': 'questionsubjective',
            },
        ),
        migrations.AlterModelOptions(
            name='questionsingle',
            options={'verbose_name': '单项选择题', 'verbose_name_plural': '单项选择题'},
        ),
    ]
