# Generated by Django 3.1 on 2020-10-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20201029_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsubjective',
            name='remark',
            field=models.CharField(max_length=64, null=True, verbose_name='备注'),
        ),
    ]
