# Generated by Django 3.1 on 2020-10-26 02:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rbac', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('birth', models.DateField(auto_created=True, null=True, verbose_name='出生日期')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='学号')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='姓名')),
                ('password', models.CharField(default='123', max_length=128, verbose_name='密码')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女'), ('中性', '中性')], default='中性', max_length=8, verbose_name='性别')),
                ('email', models.EmailField(max_length=64, null=True, verbose_name='电子邮件')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'student',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='学院名称')),
            ],
            options={
                'verbose_name': '学院信息表',
                'verbose_name_plural': '学院信息表',
                'db_table': 'institute',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=64, null=True, verbose_name='专业名称')),
                ('iid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.institute', verbose_name='学院名称')),
            ],
            options={
                'verbose_name': '专业信息表',
                'verbose_name_plural': '专业信息表',
                'db_table': 'profession',
                'unique_together': {('career',)},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, verbose_name='科目')),
                ('grade', models.IntegerField(verbose_name='成绩')),
                ('sid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '成绩表',
                'verbose_name_plural': '成绩表',
                'db_table': 'grade',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academy',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.institute', verbose_name='所在学院'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.profession', verbose_name='所在专业'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.role'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
