# Generated by Django 3.1 on 2020-09-28 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSingle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20, verbose_name='科目')),
                ('title', models.TextField(verbose_name='题目')),
                ('optionA', models.CharField(max_length=30, verbose_name='A选项')),
                ('optionB', models.CharField(max_length=30, verbose_name='B选项')),
                ('optionC', models.CharField(max_length=30, verbose_name='C选项')),
                ('optionD', models.CharField(max_length=30, verbose_name='D选项')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, verbose_name='答案')),
                ('level', models.CharField(choices=[('1', 'easy'), ('2', 'common'), ('3', 'difficult')], max_length=16, verbose_name='等级难度')),
                ('score', models.IntegerField(verbose_name='分数')),
            ],
            options={
                'verbose_name': '单项选择表',
                'verbose_name_plural': '单项选择表',
                'db_table': 'questionsingle',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女'), ('中性', '中性')], max_length=8, verbose_name='性别')),
                ('academy', models.CharField(choices=[('计算机与通信学院', '计算机与通信学院'), ('电气与自动化学院', '电气与自动化学院'), ('外国语学院', '外国语学院'), ('理学院', '理学院'), ('土木工程学院', '土木工程学院')], max_length=32, verbose_name='所在学院')),
                ('profession', models.CharField(max_length=64, verbose_name='专业')),
                ('password', models.CharField(default='123', max_length=24, verbose_name='密码')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='邮箱')),
                ('birth', models.DateField(verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='教工号')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女'), ('中性', '中性')], max_length=8, verbose_name='性别')),
                ('academy', models.CharField(choices=[('计算机与通信学院', '计算机与通信学院'), ('电气与自动化学院', '电气与自动化学院'), ('外国语学院', '外国语学院'), ('理学院', '理学院'), ('土木工程学院', '土木工程学院')], max_length=32, verbose_name='所在学院')),
                ('password', models.CharField(default='123', max_length=24, verbose_name='密码')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='邮箱')),
                ('birth', models.DateField(verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64, verbose_name='科目')),
                ('profession', models.CharField(max_length=64, verbose_name='试卷适用专业')),
                ('examtime', models.DateTimeField(verbose_name='考试时间')),
                ('pid', models.ManyToManyField(to='app01.QuestionSingle')),
                ('tid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.teacher')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'paper',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=16, primary_key=True, serialize=False, verbose_name='id')),
                ('subject', models.CharField(max_length=20, verbose_name='科目')),
                ('grade', models.IntegerField(verbose_name='成绩')),
                ('sid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.student')),
            ],
            options={
                'verbose_name': '成绩表',
                'verbose_name_plural': '成绩表',
                'db_table': 'grade',
            },
        ),
    ]
