# Generated by Django 3.1 on 2020-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='sid',
            new_name='学生',
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('中性', '中性')], default='中性', max_length=8, verbose_name='性别'),
        ),
    ]
