# Generated by Django 3.1 on 2020-10-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20201026_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='role',
            new_name='roles',
        ),
    ]
