# Generated by Django 3.1 on 2020-09-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200928_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='pid',
            new_name='单项选择',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='tid',
            new_name='所属教师',
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
