# Generated by Django 3.1 on 2020-09-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200928_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='单项选择',
        ),
        migrations.AddField(
            model_name='paper',
            name='pid',
            field=models.ManyToManyField(related_name='xxx', to='app01.QuestionSingle'),
        ),
    ]
