# Generated by Django 3.1 on 2020-09-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200928_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='pid',
        ),
        migrations.AddField(
            model_name='paper',
            name='单项选择',
            field=models.ManyToManyField(db_table='paper_pid', to='app01.QuestionSingle'),
        ),
    ]
