# Generated by Django 3.1 on 2020-09-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_paper_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='a',
            field=models.ForeignKey(choices=[('计算机与通信学院', '计算机与通信学院'), ('电气与自动化学院', '电气与自动化学院'), ('外国语学院', '外国语学院'), ('理学院', '理学院'), ('土木工程学院', '土木工程学院')], default='', on_delete=django.db.models.deletion.CASCADE, to='app01.student'),
        ),
    ]
