# Generated by Django 3.1 on 2020-10-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('app01', '0007_remove_userprofile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='rbac.Role'),
        ),
    ]
