# Generated by Django 3.1 on 2020-09-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20200928_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='学院名称')),
            ],
            options={
                'verbose_name': '学院信息表',
                'verbose_name_plural': '学院信息表',
                'db_table': 'institute',
                'unique_together': {('name',)},
            },
        ),
        migrations.RemoveField(
            model_name='paper',
            name='a',
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=64, verbose_name='专业名称')),
                ('学院名称', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.institute')),
            ],
            options={
                'verbose_name': '专业信息表',
                'verbose_name_plural': '专业信息表',
                'db_table': 'profession',
                'unique_together': {('career',)},
            },
        ),
    ]
