# Generated by Django 3.1 on 2020-09-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20200928_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academy',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profession',
        ),
        migrations.AddField(
            model_name='student',
            name='所在专业',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.profession'),
        ),
        migrations.AddField(
            model_name='student',
            name='所在学院',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.institute'),
        ),
    ]
