# Generated by Django 3.1 on 2020-10-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_paper_status'),
        ('app01', '0008_userprofile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.paper', verbose_name='科目'),
        ),
    ]
