# Generated by Django 3.1 on 2020-09-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20200928_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='所在专业',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.profession', to_field='career'),
        ),
    ]
