# Generated by Django 3.1 on 2020-09-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20200928_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='所在专业',
        ),
    ]
