# Generated by Django 3.1 on 2020-09-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_remove_student_所在专业'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profession',
            field=models.CharField(default='', max_length=32, verbose_name='所在学院'),
        ),
    ]
