# Generated by Django 3.1 on 2020-09-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20200928_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='单项选择',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='所属教师',
            new_name='tid',
        ),
    ]
